jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN&#58; &#36;&#123;&#123; secrets.SNYK_TOKEN &#125;&#125;
        with:
          command: monitor

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js &#36;&#123;&#123; matrix.node-version &#125;&#125;
        uses: actions/setup-node@v2
        with:
          node-version&#58; &#36;&#123;&#123; matrix.node-version &#125;&#125;
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test